services:
    OHMedia\MetaBundle\Twig\MetaExtension:
        arguments: ["@oh_media_file.file_manager", "@oh_media_meta.meta_settings", "%kernel.project_dir%"]
        tags: ["twig.extension"]

    OHMedia\MetaBundle\Settings\MetaSettings:
        autowire: true

    oh_media_meta.meta_settings:
        alias: OHMedia\MetaBundle\Settings\MetaSettings

    OHMedia\MetaBundle\Settings\MetaImageTransformer:
        autowire: true
        tags: ["oh_media_settings.transformer"]

    OHMedia\MetaBundle\Repository\MetaRepository:
        autowire: true
        tags: ["doctrine.repository_service"]
