services:
    OHMedia\MetaBundle\Twig\MetaExtension:
        arguments: ["@oh_media_settings.settings"]
        tags:
            - { name: twig.extension }

    OHMedia\MetaBundle\Settings\ImageTransformer:
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: oh_media_settings.transformer }

    oh_media_meta.settings:
        alias: OHMedia\MetaBundle\Settings\ImageTransformer
